### ISSUE TITLE
Roadmap v0.1

### ISSUE THREAD

**Issue by D2Lark** [D2Lark/how-query-engine-work#1]
Load data from csv and execute a simple select statement

- [ ] Complete datasource module and unit tests
- [ ] Complete datatypes module and unit tests
- [ ] Complete execution module and unit tests
- [ ] Complete logicalplan module and unit tests
- [ ] Complete optimizer module and unit tests
- [ ] Complete physicalplan module and unit tests
- [ ] Complete queryplane rmodule and unit tests
- [ ] Complete optimizer module and unit tests
- [ ] Complete optimizer module and unit tests
